version: '3.3'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: hello
      MYSQL_USER: world
      MYSQL_PASSWORD: supersecret



  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./projectile:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

#volumes:
#  projectile:
#  data:

  